<?php

namespace ContainerTLpLxGV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckoutControllercheckoutService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.6OFbbN7.App\Controller\CheckoutController::checkout()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6OFbbN7.App\\Controller\\CheckoutController::checkout()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'stripeService' => ['privates', 'App\\Service\\StripeService', 'getStripeServiceService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', true],
        ], [
            'stripeService' => 'App\\Service\\StripeService',
            'logger' => '?',
        ]))->withContext('App\\Controller\\CheckoutController::checkout()', $container);
    }
}
