<?php

namespace ContainerQ1ZdBVk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_AnonymousService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.config.anonymous' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-bundle'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'FirewallConfig.php';

        return $container->privates['security.firewall.map.config.anonymous'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('anonymous', 'security.user_checker', '.security.request_matcher.jor1Ghd', true, false, 'security.user.provider.concrete.in_database', 'anonymous', NULL, NULL, NULL, [], NULL, NULL);
    }
}
