<?php

namespace ContainerUuUdbCw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertyInfo_CacheService extends App_KernelProdContainer
{
    /*
     * Gets the private 'property_info.cache' shared service.
     *
     * @return \Symfony\Component\PropertyInfo\PropertyInfoCacheExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['property_info.cache'] = new \Symfony\Component\PropertyInfo\PropertyInfoCacheExtractor(($container->privates['property_info.cache.inner'] ?? $container->load('getPropertyInfo_Cache_InnerService')), ($container->privates['cache.property_info'] ?? $container->load('getCache_PropertyInfoService')));
    }
}
