<?php

namespace ContainerUuUdbCw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\RoleController' shared autowired service.
     *
     * @return \App\Controller\RoleController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\RoleController'] = $instance = new \App\Controller\RoleController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\RoleController', $container));

        return $instance;
    }
}
