<?php

namespace ContainerUuUdbCw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_AnonymousService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.map.config.anonymous' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.firewall.map.config.anonymous'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('anonymous', 'security.user_checker', '.security.request_matcher.jor1Ghd', true, false, 'security.user.provider.concrete.in_database', 'anonymous', NULL, NULL, NULL, [], NULL, NULL);
    }
}
