when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: "%kernel.project_dir%/logs/%kernel.environment%.log"
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                path: "%kernel.project_dir%/logs/deprecation.log"
                level: info
                formatter: monolog.formatter.json
                channels: ["deprecation"]  # Utilisez des crochets pour définir le canal