security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUser Interface: 'auto'
        App\Entity\User:
            algorithm: bcrypt

    providers:
        in_database:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: in_database
            form_login:
                login_path: security_login
                check_path: security_login_check
                default_target_path: /home_connected
            logout:
                path: security_logout
                target: /

        anonymous:
            lazy: true
            provider: in_database
            pattern: ^/

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/checkout, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/admin, roles: ROLE_ADMIN }

        # - { path: ^/profile, roles: ROLE_USER }
        # - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
