app_forgot_password:
    path: /forgot-password
    controller: App\Controller\SecurityController::forgotPassword

security_login:
    path: /connexion
    controller: App\Controller\SecurityController::login

security_login_check:
    path: /login
    controller: App\Controller\SecurityController::login

security_logout:
    path: /deconnexion
    controller: App\Controller\SecurityController::logout
