<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ5LJzJv\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ5LJzJv/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQ5LJzJv.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQ5LJzJv\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQ5LJzJv\App_KernelProdContainer([
    'container.build_hash' => 'Q5LJzJv',
    'container.build_id' => '2f98e90a',
    'container.build_time' => 1743284535,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ5LJzJv');
