<?php

namespace Container80TLRBN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerregistrationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.98d_3.5.App\Controller\SecurityController::registration()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.98d_3.5.App\\Controller\\SecurityController::registration()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'passwordHasher' => ['privates', '.errored.dslSmea', NULL, 'Cannot determine controller argument for "App\\Controller\\SecurityController::registration()": the $passwordHasher argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordHasherInterface".'],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\SecurityController::registration()', $container);
    }
}
