<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTLpLxGV\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTLpLxGV/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerTLpLxGV.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerTLpLxGV\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerTLpLxGV\App_KernelTestDebugContainer([
    'container.build_hash' => 'TLpLxGV',
    'container.build_id' => 'dce6c788',
    'container.build_time' => 1742590887,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTLpLxGV');
