<?php

namespace ContainerQ5LJzJv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TsLFVl9Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.tsLFVl9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tsLFVl9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CheckoutController::checkout' => ['privates', '.service_locator.6OFbbN7.App\\Controller\\CheckoutController::checkout()', 'getCheckoutControllercheckoutService', true],
            'App\\Controller\\HomeController::show' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\HomeController::show()', 'getHomeControllershowService', true],
            'App\\Controller\\RoleController::addRole' => ['privates', '.service_locator.egipcEH.App\\Controller\\RoleController::addRole()', 'getRoleControlleraddRoleService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.98d_3.5.App\\Controller\\SecurityController::registration()', 'getSecurityControllerregistrationService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController::activateAccount' => ['privates', '.service_locator.d8rsN5P.App\\Controller\\SecurityController::activateAccount()', 'getSecurityControlleractivateAccountService', true],
            'App\\Controller\\SecurityController::forgotPassword' => ['privates', '.service_locator.XwKcc_z.App\\Controller\\SecurityController::forgotPassword()', 'getSecurityControllerforgotPasswordService', true],
            'App\\Controller\\SecurityController::resetPassword' => ['privates', '.service_locator.OLhm2sr.App\\Controller\\SecurityController::resetPassword()', 'getSecurityControllerresetPasswordService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CheckoutController:checkout' => ['privates', '.service_locator.6OFbbN7.App\\Controller\\CheckoutController::checkout()', 'getCheckoutControllercheckoutService', true],
            'App\\Controller\\HomeController:show' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\HomeController::show()', 'getHomeControllershowService', true],
            'App\\Controller\\RoleController:addRole' => ['privates', '.service_locator.egipcEH.App\\Controller\\RoleController::addRole()', 'getRoleControlleraddRoleService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.98d_3.5.App\\Controller\\SecurityController::registration()', 'getSecurityControllerregistrationService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController:activateAccount' => ['privates', '.service_locator.d8rsN5P.App\\Controller\\SecurityController::activateAccount()', 'getSecurityControlleractivateAccountService', true],
            'App\\Controller\\SecurityController:forgotPassword' => ['privates', '.service_locator.XwKcc_z.App\\Controller\\SecurityController::forgotPassword()', 'getSecurityControllerforgotPasswordService', true],
            'App\\Controller\\SecurityController:resetPassword' => ['privates', '.service_locator.OLhm2sr.App\\Controller\\SecurityController::resetPassword()', 'getSecurityControllerresetPasswordService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CheckoutController::checkout' => '?',
            'App\\Controller\\HomeController::show' => '?',
            'App\\Controller\\RoleController::addRole' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::activateAccount' => '?',
            'App\\Controller\\SecurityController::forgotPassword' => '?',
            'App\\Controller\\SecurityController::resetPassword' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CheckoutController:checkout' => '?',
            'App\\Controller\\HomeController:show' => '?',
            'App\\Controller\\RoleController:addRole' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:activateAccount' => '?',
            'App\\Controller\\SecurityController:forgotPassword' => '?',
            'App\\Controller\\SecurityController:resetPassword' => '?',
        ]);
    }
}
