<?php

namespace ContainerQ5LJzJv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineMigrations_SchemaFilterListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'doctrine_migrations.schema_filter_listener' shared service.
     *
     * @return \Doctrine\Bundle\MigrationsBundle\EventListener\SchemaFilterListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['doctrine_migrations.schema_filter_listener'] = new \Doctrine\Bundle\MigrationsBundle\EventListener\SchemaFilterListener('doctrine_migration_versions');
    }
}
