<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVKYZotL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVKYZotL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVKYZotL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVKYZotL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVKYZotL\App_KernelDevDebugContainer([
    'container.build_hash' => 'VKYZotL',
    'container.build_id' => '7da1968a',
    'container.build_time' => 1743608511,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVKYZotL');
